import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { ReportSpec, logger } from '@repo/shared';

export const generatePDF = (report: ReportSpec, filename: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reportsDir = path.resolve(process.cwd(), 'reports');
    
    // Ensure reports dir exists (it should, but good practice)
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const outputPath = path.join(reportsDir, filename);
    logger.info(`Generating PDF at: ${outputPath}`);

    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(outputPath);

    doc.pipe(stream);

    // Title Page
    doc.fontSize(24).text(report.title, { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text('Generated by AI Research Agent', { align: 'center' });
    doc.moveDown(4);

    // Summary
    doc.fontSize(16).text('Executive Summary');
    doc.moveDown(0.5);
    doc.fontSize(12).text(report.summary, { align: 'justify' });
    doc.moveDown(2);

    // Sections
    report.sections.forEach((section) => {
      doc.addPage();
      doc.fontSize(18).text(section.heading);
      doc.moveDown(1);
      doc.fontSize(12).text(section.content, { align: 'justify' });
    });

    // References
    if (report.references && report.references.length > 0) {
      doc.addPage();
      doc.fontSize(18).text('References');
      doc.moveDown(1);
      report.references.forEach((ref) => {
        doc.fontSize(12).fillColor('blue').text(ref.title, { link: ref.url, underline: true });
        doc.moveDown(0.5);
      });
    }

    doc.end();

    stream.on('finish', () => {
      logger.info(`PDF generated successfully: ${outputPath}`);
      resolve(outputPath);
    });

    stream.on('error', (err) => {
      logger.error(`Error generating PDF: ${err}`);
      reject(err);
    });
  });
};

